[package]
name = "newral-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
mnist = "0.5.0"
serde = "1.0.156"
serde_json = "1.0.94"
